xiin:
  home:
    url: 'http://pyne.googlecode.com'

  modules:
    exclude   : '.svn'
    ext       : [ 'svn', 'yml' ]
    directory :
      url: '/svn/branches/testing/PyneTools/xiin/source/'
    text:
      url:
        list  : '{0}{1}'
        full  : '{0}{1}/{2}'
        module: '{0}/{1}'

  report:
    elipse: '...'
    error: []

  test:
    home:
      url: '/.inxi/xiin/'
